language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t pr2n33th/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true pr2n33th/react-test npm test 

after_success:
  - docker build -t pr2n33th/multi-client ./client 
  - docker build -t pr2n33th/multi-nginx ./nginx 
  - docker build -t pr2n33th/multi-server ./server 
  - docker build -t pr2n33th/multi-worker ./worker 

  # Logging in to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # pushing images to docker hub
  - docker push pr2n33th/multi-client
  - docker push pr2n33th/multi-nginx
  - docker push pr2n33th/multi-server
  - docker push pr2n33th/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker-multi"
  env: "Docker-multi-env"
  bucket_name: "elasticbeanstalk-eu-north-1-542701547676"
  bucker_path: "docker-multi"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
